### PR TITLE
[Issue #4] Edit of the database

### PR DESCRIPTION
**Pull request by AlicjaKowalska**
Implemented edit funcionality of the database.

### CODE REVIEW

**Review by kozych — COMMENTED** [review]
looks good, please resolve the conflicts

**Comment by piotrgos45** [comment]
looks good for me

**Comment by AlicjaKowalska** [comment]
> looks good, please resolve the conflicts

done

**Review by kozych — APPROVED** [review]

**Review by piotrgos45 — APPROVED** [review]

**Comment by michalmobi** [comment]
"Edition" sounds like "version" to me. I guess this word should be replaced by "edit" (in PR title and in code).

**Review by michalmobi — APPROVED** [review]

**Pull request merged**
